### ISSUE TITLE
Why dont i see the web UI for PHPCI

### ISSUE THREAD

**Issue by apilkarki** [sunfoxcz/docker-phpci#1]
@foxycode 
Hello there !!
What specific value are you trying to point on these two variables ?
  - PHPCI_URL=http://phpci.domain.tld
    - PHPCI_DB_HOST=mysql.domain.tld
BTW i have used,
  - PHPCI_URL=http://localhost:port
    - PHPCI_DB_HOST=mysql (service name in my composer file)
After a long struggle i get welcome msg from PHPCI but dont see the UI on the browser. 
Can u please guide me on it ?

**Comment by foxycode** [comment]
Hello,

`PHPCI_URL` is where you want to access PHPCI. It is what I have configured in nginx reverse proxy, which proxies requests to docker container IP and port. `PHPCI_DB_HOST` set to service is of MySQL server in `docker-compose.yml` is proper setting.

My litely censored production config:
```yaml
phpci:
  container_name: phpci
  image: sunfoxcz/phpci:0.1.2
  environment:
    - TZ=Europe/Prague
    - PHPCI_URL=https://phpci.mydomain.cz
    - PHPCI_DB_HOST=mysql.mydomain.cz
    - PHPCI_DB_NAME=phpci
    - PHPCI_DB_PASSWORD=xxx
    - PHPCI_ADMIN_LOGIN=admin
    - PHPCI_ADMIN_PASSWORD=xxx
    - PHPCI_ADMIN_MAIL=admin@mydomain.cz
  ports:
    - "127.0.0.1:8101:80"
  links:
    - mysql
mysql:
  container_name: testdb
  image: percona:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=xxx
```

My nginx zone looks like this:
```
server {
    # ...
    server_name phpci.mydomain.cz;

    location / {
        proxy_pass http://127.0.0.1:8101;
    }
}
```

Let me know if it works.

**Comment by apilkarki** [comment]
@foxycode  @foxycode 
My compose.yml looks like

```
phpci:
  container_name: phpci
  image: sunfoxcz/phpci:0.1.2
  environment:
    - TZ=Europe/Prague
    - PHPCI_URL=http://localhost:8000
    - PHPCI_DB_HOST=mysql
    - PHPCI_DB_USER=root
    - PHPCI_DB=phpci
    - PHPCI_DB_PASSWORD=secret
    - PHPCI_ADMIN_LOGIN=admin
    - PHPCI_ADMIN_PASSWORD=xxx
    - PHPCI_ADMIN_MAIL=admin@mydomain.cz
  ports:
    - "127.0.0.1:8101:8000"
  links:
    - mysql
mysql:
  container_name: testdb
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=phpci
  ports:
    - "3306:3306"
```
i can acess my sql container on `http://localhost:3306` but cannot get the PHPCI UI on `http://localhost:8000`
What am i doing wrong ? 
Instead i want it to execute locally rather than pass it through reverse proxy.
